apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-demo
  template:
    metadata:
      labels:
        app: azure-demo
    spec:
      containers:
      - name: azure-demo-container
        image: azure-demo-app
        ports:
        - containerPort: 5000
