apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-my
  template:
    metadata:
      labels:
        app: azure-my
    spec:
      containers:
      - name: azure-my-container
        image: azure-my-app
        ports:
        - containerPort: 5000
